/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic.boilerplate;

import java.util.Vector;

public class App {

    private Neighbourhood neighbourhood;

    public App(Vector<Cell> cells) {
        this.neighbourhood = new Neighbourhood(cells);
    }

    public void letLifeFoundAWay() {
        neighbourhood.bloom();
    }

}
